"""empty message

Revision ID: 1d28bffd8ff7
Revises: 2c1f37a5d964
Create Date: 2026-03-01 04:52:10.436027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d28bffd8ff7'
down_revision: Union[str, Sequence[str], None] = '2c1f37a5d964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('properties_zpid_key'), 'properties', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('properties_zpid_key'), 'properties', ['zpid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
