"""empty message

Revision ID: 2c1f37a5d964
Revises: aa3debeeebb4
Create Date: 2026-03-01 01:55:14.943662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1f37a5d964'
down_revision: Union[str, Sequence[str], None] = 'aa3debeeebb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('zpid', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('state', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('price_per_sqft', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('price_change', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('price_changed_date', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('listing_status', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('days_on_zillow', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('listing_date', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('lot_size', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('lot_size_unit', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('year_built', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('is_new_construction', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('zestimate', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('rent_zestimate', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('tax_assessed_value', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('tax_assessment_year', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('has_vr_model', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('has_videos', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('has_floor_plan', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('is_showcase_listing', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('open_house_start', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('open_house_end', sa.DateTime(), nullable=True))
    op.add_column('properties', sa.Column('broker_name', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('photo_url', sa.String(), nullable=True))
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'beds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'baths',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('properties', 'sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint(None, 'properties', ['zpid'])
    op.drop_column('properties', 'address')
    op.drop_column('properties', 'school_score')
    op.drop_column('properties', 'commute_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('commute_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('school_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'properties', type_='unique')
    op.alter_column('properties', 'sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('properties', 'baths',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('properties', 'beds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('properties', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('properties', 'photo_url')
    op.drop_column('properties', 'broker_name')
    op.drop_column('properties', 'open_house_end')
    op.drop_column('properties', 'open_house_start')
    op.drop_column('properties', 'is_showcase_listing')
    op.drop_column('properties', 'has_floor_plan')
    op.drop_column('properties', 'has_videos')
    op.drop_column('properties', 'has_vr_model')
    op.drop_column('properties', 'tax_assessment_year')
    op.drop_column('properties', 'tax_assessed_value')
    op.drop_column('properties', 'rent_zestimate')
    op.drop_column('properties', 'zestimate')
    op.drop_column('properties', 'is_new_construction')
    op.drop_column('properties', 'year_built')
    op.drop_column('properties', 'lot_size_unit')
    op.drop_column('properties', 'lot_size')
    op.drop_column('properties', 'listing_date')
    op.drop_column('properties', 'days_on_zillow')
    op.drop_column('properties', 'listing_status')
    op.drop_column('properties', 'price_changed_date')
    op.drop_column('properties', 'price_change')
    op.drop_column('properties', 'price_per_sqft')
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'state')
    op.drop_column('properties', 'street_address')
    op.drop_column('properties', 'zpid')
    # ### end Alembic commands ###
