"""empty message

Revision ID: aa3debeeebb4
Revises: c56e7cee3196
Create Date: 2026-02-28 20:56:44.916570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3debeeebb4'
down_revision: Union[str, Sequence[str], None] = 'c56e7cee3196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('liked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'liked')
    # ### end Alembic commands ###
